# Generated by Django 3.1.5 on 2021-01-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='password',
            field=models.CharField(default=11, max_length=18),
            preserve_default=False,
        ),
    ]
