# Generated by Django 3.1.5 on 2021-01-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_user_model_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.user_model'),
        ),
    ]
