# Generated by Django 3.1.5 on 2021-01-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_bought_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_item',
            name='quantity',
            field=models.CharField(default='20kg', max_length=20),
        ),
    ]
